# -*- mode: ruby -*-
# vi: set ft=ruby :
BOX_URI = ENV['BOX_URI'] || "http://dump.home.lan:9090/windows_2012_r2_virtualbox.box"
PRIVATE_NETWORK = ENV['PRIVATE_NETWORK'] || '192.168.3.2'

Vagrant.configure("2") do |config|
    config.vm.define "vagrant-windows-2012-r2"
    config.vm.box = "windows_2012_r2"
    config.vm.box_url = BOX_URI

    # You should be using the vagrant-windows Vagrant Plugin!
    # Admin user name and password
    config.winrm.username = "vagrant"
    config.winrm.password = "vagrant"
    
    config.vm.guest = :windows  
    config.windows.halt_timeout = 15
    
    # Port forward WinRM and RDP
    config.vm.network "private_network", ip: PRIVATE_NETWORK
    config.vm.network :forwarded_port, guest: 3389, host: 3389
    config.vm.network :forwarded_port, guest: 5985, host: 5985
    
    # Berkshelf
    # config.berkshelf.enabled = true
    
    # Shell - Hello World
    # config.vm.provision :shell, :inline => "C:\\vagrant\\scripts\\HelloWorld.bat"
    
    config.vm.provider :virtualbox do |v, override|
        v.gui = true
        v.customize ["modifyvm", :id, "--memory", 2048]
        v.customize ["modifyvm", :id, "--cpus", 2] 
    end
    
    config.vm.provider :vmware_fusion do |v, override|
        #v.gui = true
        v.vmx["memsize"] = "2048"
        v.vmx["ethernet0.virtualDev"] = "vmxnet3"
        v.vmx["RemoteDisplay.vnc.enabled"] = "false"
        v.vmx["RemoteDisplay.vnc.port"] = "5900"
    end
    
    config.vm.provider :vmware_workstation do |v, override|
        #v.gui = true
        v.vmx["memsize"] = "2048"
        v.vmx["ethernet0.virtualDev"] = "vmxnet3"
        v.vmx["RemoteDisplay.vnc.enabled"] = "false"
        v.vmx["RemoteDisplay.vnc.port"] = "5900"
    end
end
